In [64]:
import mlrose
import numpy as np


In [80]:
fitness = mlrose.FourPeaks(t_pct=0.20)

In [81]:
init_state = np.array([0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1])

In [89]:
problem = mlrose.DiscreteOpt(length = 12, fitness_fn = fitness, maximize = True, max_val = 2)

## RHC

In [90]:
best_state, best_fitness = mlrose.random_hill_climb(problem, max_attempts=10, max_iters=100, restarts=0, init_state=init_state)

In [91]:
print(best_state)

[0 0 0 1 0 0 0 0 0 1 1 1]


In [92]:
print(best_fitness)

0.0


## GA

In [93]:
best_state, best_fitness = mlrose.genetic_alg(problem, mutation_prob = 0.2, max_attempts = 100)

In [94]:
print(best_state)

[1 1 1 1 0 0 0 0 0 0 0 0]


In [95]:
print(best_fitness)

20.0


## MIMIC

In [96]:
best_state, best_fitness = mlrose.mimic(problem, pop_size=200, keep_pct=0.2, max_attempts=10, max_iters=1000)

In [97]:
print(best_state)

[1 1 1 1 1 1 1 1 0 0 0 0]


In [98]:
print(best_fitness)

20.0


## SA

In [99]:
best_state, best_fitness = mlrose.simulated_annealing(problem,max_attempts = 10, max_iters = 10000, init_state = init_state)

In [100]:
print(best_state)

[1 1 1 1 1 1 1 1 0 0 0 0]


In [101]:
print(best_fitness)

20.0
