## <font color='red'>  is it better to have a lower fitness function value  </font>


In [6]:
import mlrose
import numpy as np

In [7]:
fitness = mlrose.Queens()

## Simulated Anealing

In [8]:
# Define alternative N-Queens fitness function for maximization problem
def queens_max(state):

   # Initialize counter
    fitness_cnt = 0

          # For all pairs of queens
    for i in range(len(state) - 1):
        for j in range(i + 1, len(state)):

                # Check for horizontal, diagonal-up and diagonal-down attacks
            if (state[j] != state[i]) \
                and (state[j] != state[i] + (j - i)) \
                and (state[j] != state[i] - (j - i)):

                   # If no attacks, then increment counter
                fitness_cnt += 1

        return fitness_cnt

# Initialize custom fitness function object
fitness_cust = mlrose.CustomFitness(queens_max)

In [22]:
problem = mlrose.DiscreteOpt(length = 8, fitness_fn = fitness, maximize = True, max_val = 8)

In [23]:
 # Define decay schedule
schedule = mlrose.ExpDecay()

# Define decay schedule
schedule = mlrose.ExpDecay()

# Define initial state
init_state = np.array([0, 1, 2, 3, 4, 5, 6, 7])

# Set random seed
np.random.seed(1)

# Solve problem using simulated annealing
best_state, best_fitness = mlrose.simulated_annealing(problem, schedule = schedule,
                                                      max_attempts = 100, max_iters = 1000,
                                                      init_state = init_state)



In [24]:
print(best_state)

[0 1 2 3 4 5 6 7]


In [25]:
print(best_fitness)

28.0


## Genetic Algorithm

In [26]:
# # Define decay schedule
# schedule = mlrose.ExpDecay()

# # Define initial state
# init_state = np.array([0, 1, 2, 3, 4, 5, 6, 7])

# # Set random seed
# np.random.seed(1)

# Solve problem using simulated annealing
best_state, best_fitness = mlrose.genetic_alg(problem, pop_size=200, mutation_prob=0.1, max_attempts=10, max_iters=1000)

In [27]:
print(best_state)

[7 7 7 7 7 7 7 1]


In [28]:
print(best_fitness)

22.0


## Random Hill Climbing

In [29]:
# # Define decay schedule
# schedule = mlrose.ExpDecay()

# # Define initial state
# init_state = np.array([0, 1, 2, 3, 4, 5, 6, 7])

# # Set random seed
# np.random.seed(1)

# Solve problem using simulated annealing
best_state, best_fitness = mlrose.random_hill_climb(problem, max_attempts=10, max_iters=1000, restarts=0, init_state=init_state)

In [30]:
print(best_state)

[0 1 2 3 4 5 6 7]


In [31]:
print(best_fitness)

28.0


## MIMIC

In [32]:
# # Define decay schedule
# schedule = mlrose.ExpDecay()

# # Define initial state
# init_state = np.array([0, 1, 2, 3, 4, 5, 6, 7])

# # Set random seed
# np.random.seed(1)

# Solve problem using simulated annealing
best_state, best_fitness = mlrose.mimic(problem, pop_size=200, keep_pct=0.2, max_attempts=10, max_iters=1000)

In [33]:
print(best_state)

[6 6 6 6 6 2 6 6]


In [34]:
print(best_fitness)

22.0
